Update bundler for Travis
Apparently, there's an issue with some of the versions causing a
NoMethodError.

  NoMethodError: undefined method `spec' for nil:NilClass